[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "calculator_pkg_jsk"
version = "0.1.0"

[project.scripts]
icalculator_pkg_jsk = "calculator_pkg_jsk.__main__:main"

